apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - ingress.yml
  - service.yml
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - redis-pvc.yml
  - redis-deployment.yml
  - redis-service.yml
